theme: jekyll-theme-minimal
show_downloads: true
github:
  zip_url: https://github.com/paulahitz8/DonkeyKong/releases/download/v.alpha/DeleteTeemo_DonkeyKong_v.alpha.zip
  tar_url: https://github.com/paulahitz8/DonkeyKong/releases/download/v.alpha/DeleteTeemo_DonkeyKong_v.alpha.zip
